# -*- coding: utf-8 -*-
"""hospital readmission

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtWVr21tNkNLiiKP2tkJFkzZrGjAJsAZ
"""

## _ _ _ Import Libraries _ _ _

# !pip install ydata-profiling
# from ydata_profiling import ProfileReport
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
import joblib, datetime


## _ _ _ Load Dataset _ _ _

df_original = pd.read_csv('/content/hospital_readmission_dataset.csv')
hospital_readmission = df_original.copy()


## _ _ _ Logic To Keep, Combine, or Drop Columns _ _ _

# season : captures seasonal health effects (flu, allergy, heat-related conditions)
# age, gender : biological factors that may influence readmission risk
# region : location-based environmental or healthcare access differences
# primary_diagnosis : different diseases have different severity and readmission patterns
# length_of_stay : reflects illness severity or early/late discharge effects
# treatment_type : different treatments may carry different recovery risks
# followup_visits_last_year : follow-up care may reduce readmission by detecting issues early
# prev_readmissions : past readmission history is a strong predictor of future risk
# insurance_type : reflects healthcare access, affordability, and follow-up availability
# discharge_disposition : post-discharge care setting influences readmission risk
# patient_complexity_score : combines comorbidities_count + medications_count (engineered)
# Target : readmission_risk_score — regression target
# Dropped : label → would cause data leakage (derived from the target)


## _ _ _ Feature Engineering _ _ _

hospital_readmission['patient_complexity_score'] = (hospital_readmission['comorbidities_count'] + hospital_readmission['medications_count'])
hospital_readmission = hospital_readmission.drop(columns=['patient_id', 'admission_date', 'comorbidities_count', 'medications_count', 'label'])
hospital_readmission.head()
# profile = ProfileReport(hospital_readmission)
# profile.to_notebook_iframe()
# profile.to_file("report.html")


## _ _ _ Model Feed _ _ _

X = hospital_readmission.drop(columns=['readmission_risk_score'])
y = hospital_readmission['readmission_risk_score']
print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

categorical_cols = ['season', 'gender', 'region', 'primary_diagnosis', 'treatment_type', 'insurance_type', 'discharge_disposition']
numeric_cols     = ['age', 'length_of_stay', 'patient_complexity_score', 'followup_visits_last_year', 'prev_readmissions']

preprocessor = ColumnTransformer(transformers=[
    ('cat', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'), categorical_cols),
    ('num', StandardScaler(), numeric_cols)
], remainder='drop', verbose_feature_names_out=False)

models = {
    'LinearRegression'  : LinearRegression(),
    'Ridge'             : Ridge(),
    'DecisionTree'      : DecisionTreeRegressor(random_state=42),
    'RandomForest'      : RandomForestRegressor(random_state=42, n_jobs=-1),
    'GradientBoosting'  : GradientBoostingRegressor(random_state=42),
    'XGBoost'           : XGBRegressor(random_state=42, verbosity=0),
    'KNN'               : KNeighborsRegressor(n_jobs=-1),
}


## _ _ _ Model Comparison with 5-Fold Cross-Validation _ _ _

results = {} #want to store model results using names as keys.

for name, model in models.items():    #For each model in the models dictionary, creating a pipeline that first preprocesses the data, then trains the model
    pipe = Pipeline([('preprocessor', preprocessor), ('model', model)])

    cv_r2 = cross_val_score(pipe, X_train, y_train, cv=5, scoring='r2', n_jobs=-1)

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    results[name] = {
        'CV R² (mean)' : round(cv_r2.mean(), 4),   # unbiased estimate across 5 folds
        'CV R² (std)'  : round(cv_r2.std(),  4),   # stability indicator — lower is better
        'Train R²'     : round(pipe.score(X_train, y_train), 4), #how well the model explains the training data. Higher is better.
        'Test  R²'     : round(pipe.score(X_test,  y_test),  4), #how well the model performs on unseen test data.Higher is better.
        'MAE'          : round(mean_absolute_error(y_test, y_pred), 4),  # the average prediction error.Lower is better.
        'RMSE'         : round(np.sqrt(mean_squared_error(y_test, y_pred)), 4),  #measures prediction error, but it punishes large errors more than MAE.Lower is better.
        'MedAE'        : round(float(np.median(np.abs(y_test - y_pred))), 4),  # middle prediction error, more robust than MAE when outliers exist. Lower is better
    }

results_df = pd.DataFrame(results).T.sort_values('Test  R²', ascending=False)
print("_ _ _ Model Comparison _ _ _")
print(results_df.to_string())


## _ _ _ Hyperparameter Tuning (XGBoost) _ _ _

best_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', XGBRegressor(random_state=42, verbosity=0))
])

param_grid = {
     'model__n_estimators'  : [100, 200, 300],
     'model__max_depth'     : [3, 5, 7],
     'model__learning_rate' : [0.01, 0.05, 0.1],
 }

grid_search = GridSearchCV(best_pipe, param_grid, cv=5, scoring='r2', verbose=1, n_jobs=-1)
grid_search.fit(X_train, y_train)

print(f"\nBest Params : {grid_search.best_params_}")
print(f"Best CV R²  : {round(grid_search.best_score_, 4)}")

best_model   = grid_search.best_estimator_
y_pred_tuned = best_model.predict(X_test)

print("_ _ _ After Tuning _ _ _")
print(f"Train R² : {round(best_model.score(X_train, y_train), 4)}")
print(f"Test  R² : {round(best_model.score(X_test,  y_test),  4)}")
print(f"RMSE     : {round(np.sqrt(mean_squared_error(y_test, y_pred_tuned)), 4)}")
print(f"MedAE    : {round(float(np.median(np.abs(y_test - y_pred_tuned))), 4)}")

## _ _ _ Before vs After Tuning _ _ _

untuned_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', XGBRegressor(random_state=42, verbosity=0))
])
untuned_pipe.fit(X_train, y_train)
y_pred_untuned = untuned_pipe.predict(X_test)

print("_ _ _ Before Tuning _ _ _")
print(f"Test  R² : {round(untuned_pipe.score(X_test, y_test), 4)}")
print(f"RMSE     : {round(np.sqrt(mean_squared_error(y_test, y_pred_untuned)), 4)}")


## _ _ _ Model Versioning _ _ _

version  = datetime.datetime.now().strftime("%Y%m%d_%H%M")
filename = f'xgb_model_v{version}.pkl'

metadata = {
    'model'      : best_model,
    'features'   : categorical_cols + numeric_cols,
    'best_params': grid_search.best_params_,
    'test_r2'    : round(best_model.score(X_test, y_test), 4),
    'rmse'       : round(np.sqrt(mean_squared_error(y_test, y_pred_tuned)), 4),
    'trained_on' : version,
}

joblib.dump(metadata, filename)
print(f"\n _ _ _ Model Saved _ _ _")
print(f"  File        : {filename}")
print(f"  Test R²     : {metadata['test_r2']}")
print(f"  RMSE        : {metadata['rmse']}")
print(f"  Best Params : {metadata['best_params']}")


## _ _ _ Plots _ _ _

fig, axes = plt.subplots(1, 3, figsize=(17, 5))

# 1. Model comparison bar chart
r2_vals = results_df['Test  R²'].sort_values()
axes[0].barh(r2_vals.index, r2_vals.values, color='#4C72B0', edgecolor='white')
axes[0].set_title('Test R² by Model', fontweight='bold')
axes[0].set_xlabel('Test R²')
axes[0].grid(axis='x', linestyle='--', alpha=0.4)
axes[0].spines[['top','right']].set_visible(False)

# 2. Predicted vs Actual
axes[1].scatter(y_test, y_pred_tuned, alpha=0.3, s=10, color='#4C72B0')
lims = [min(y_test.min(), y_pred_tuned.min()), max(y_test.max(), y_pred_tuned.max())]
axes[1].plot(lims, lims, 'r--', linewidth=1.5, label='Perfect fit')
axes[1].set_xlabel('Actual Risk Score')
axes[1].set_ylabel('Predicted Risk Score')
axes[1].set_title('Predicted vs Actual (Tuned XGB)', fontweight='bold')
axes[1].legend()
axes[1].grid(linestyle='--', alpha=0.4)
axes[1].spines[['top','right']].set_visible(False)

# 3. XGBoost feature importance
xgb_model     = best_model.named_steps['model']
ohe           = best_model.named_steps['preprocessor'].named_transformers_['cat']
feature_names = list(ohe.get_feature_names_out(categorical_cols)) + numeric_cols
importances   = pd.Series(xgb_model.feature_importances_, index=feature_names) \
                  .sort_values().tail(15)

axes[2].barh(importances.index, importances.values, color='#55A868', edgecolor='white')
axes[2].set_title('Top 15 Feature Importances (XGB)', fontweight='bold')
axes[2].set_xlabel('Importance (Gain)')
axes[2].grid(axis='x', linestyle='--', alpha=0.4)
axes[2].spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig('model_results.png', dpi=150, bbox_inches='tight')
plt.show()